template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "erzy1239"
__REPO__ = "lang-myv"
__UND2C__ = "myv"
__UNDEFINED__ = "Erzya"
__UND__ = "myv"
