template = "https://github.com/giellalt/template-lang-und"
rev_id = 257
template_sha = "0b3fb3d8836831dedcfe3f4b9fcdc3e2aef12fa5"

[replacements]
__GLOTTOLOG_ID__ = "erzy1239"
__REPO__ = "lang-myv"
__UND2C__ = "myv"
__UNDEFINED__ = "Erzya"
__UND__ = "myv"
